MODEL_ACCESS_TIERS = {
    "free": [
        "openrouter/deepseek/deepseek-chat",
        "openrouter/qwen/qwen3-235b-a22b",
        "openrouter/google/gemini-2.5-flash-preview-05-20",
    ],
    "tier_2_20": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        "openrouter/google/gemini-2.5-flash-preview-05-20",  # Added
        "openrouter/google/gemini-2.5-pro",  # Added Gemini 2.5 Pro
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        "anthropic/claude-3-5-sonnet-latest",
        "anthropic/claude-sonnet-4-20250514",
        "openai/gpt-4.1",
        "openai/gpt-4.1-mini",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_6_50": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        "openai/gpt-4.1",
        "openai/gpt-4.1-mini",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        "openrouter/google/gemini-2.5-flash-preview-05-20",  # Added
        "openrouter/google/gemini-2.5-pro",  # Added Gemini 2.5 Pro
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        "anthropic/claude-3-5-sonnet-latest",
        "anthropic/claude-sonnet-4-20250514",
        "openai/gpt-4.1",
        "openai/gpt-4.1-mini",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_12_100": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        "openrouter/google/gemini-2.5-flash-preview-05-20",  # Added
        "openrouter/google/gemini-2.5-pro",  # Added Gemini 2.5 Pro
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        "anthropic/claude-3-5-sonnet-latest",
        "anthropic/claude-sonnet-4-20250514",
        "openai/gpt-4.1",
        "openai/gpt-4.1-mini",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_25_200": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        "openrouter/google/gemini-2.5-flash-preview-05-20",  # Added
        "openrouter/google/gemini-2.5-pro",  # Added Gemini 2.5 Pro
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        "anthropic/claude-3-5-sonnet-latest",
        "anthropic/claude-sonnet-4-20250514",
        "openai/gpt-4.1",
        "openai/gpt-4.1-mini",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_50_400": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        "openrouter/google/gemini-2.5-flash-preview-05-20",  # Added
        "openrouter/google/gemini-2.5-pro",  # Added Gemini 2.5 Pro
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        "anthropic/claude-3-5-sonnet-latest",
        "anthropic/claude-sonnet-4-20250514",
        "openai/gpt-4.1",
        "openai/gpt-4.1-mini",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_125_800": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        "openrouter/google/gemini-2.5-flash-preview-05-20",  # Added
        "openrouter/google/gemini-2.5-pro",  # Added Gemini 2.5 Pro
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        "anthropic/claude-3-5-sonnet-latest",
        "anthropic/claude-sonnet-4-20250514",
        "openai/gpt-4.1",
        "openai/gpt-4.1-mini",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_200_1000": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        "openrouter/google/gemini-2.5-flash-preview-05-20",  # Added
        "openrouter/google/gemini-2.5-pro",  # Added Gemini 2.5 Pro
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        "anthropic/claude-3-5-sonnet-latest",
        "anthropic/claude-sonnet-4-20250514",
        "openai/gpt-4.1",
        "openai/gpt-4.1-mini",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
}
MODEL_NAME_ALIASES = {
    # Short names to full names
    "sonnet-3.7": "anthropic/claude-3-7-sonnet-latest",
    "sonnet-3.5": "anthropic/claude-3-5-sonnet-latest",
    "haiku-3.5": "anthropic/claude-3-5-haiku-latest",
    "claude-sonnet-4": "anthropic/claude-sonnet-4-20250514",
    "gpt-4o": "openai/gpt-4o",
    "gpt-4.1": "openai/gpt-4.1",
    "gpt-4.1-mini": "openai/gpt-4.1-mini",
    "deepseek": "openrouter/deepseek/deepseek-chat",
    "qwen3": "openrouter/qwen/qwen3-235b-a22b",
    "gemini-flash-2.5": "openrouter/google/gemini-2.5-flash-preview-05-20",
    "gemini-2.5-flash:thinking":"openrouter/google/gemini-2.5-flash-preview-05-20:thinking",
    "google/gemini-2.5-pro-preview":"openrouter/google/gemini-2.5-pro-preview",
    "deepseek/deepseek-chat-v3-0324":"openrouter/deepseek/deepseek-chat-v3-0324",
}